#ifndef SOSH_BLTN_H_INCLUDED
#define SOSH_BLTN_H_INCLUDED

#define SOSH_BUILTIN_CMD_CHAR_C ':'
#define SOSH_BUILTIN_CMD_CHAR_S ":"

#define SOSH_BUILTIN_HELP    "help"
#define SOSH_BUILTIN_EXIT    "exit"
#define SOSH_BUILTIN_QUIT    "quit"
#define SOSH_BUILTIN_VERSION "version"
#define SOSH_BUILTIN_FILE    "file"

#define SOSH_BUILTIN_HELP_CMD \
  SOSH_BUILTIN_CMD_CHAR_S SOSH_BUILTIN_HELP
#define SOSH_BUILTIN_EXIT_CMD \
  SOSH_BUILTIN_CMD_CHAR_S SOSH_BUILTIN_EXIT
#define SOSH_BUILTIN_QUIT_CMD \
  SOSH_BUILTIN_CMD_CHAR_S SOSH_BUILTIN_QUIT
#define SOSH_BUILTIN_VERSION_CMD \
  SOSH_BUILTIN_CMD_CHAR_S SOSH_BUILTIN_VERSION
#define SOSH_BUILTIN_FILE_CMD \
  SOSH_BUILTIN_CMD_CHAR_S SOSH_BUILTIN_FILE

void sosh_builtin_exec (const char *cmd, const char *args);

#endif /* SOSH_BLTN_H_INCLUDED */

